# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-09 18:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_2d', models.IntegerField(default=0)),
                ('view_3d', models.IntegerField(default=0)),
                ('beverage', models.BooleanField(default=False)),
                ('legspace', models.IntegerField(default=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='seat',
            name='rating',
        ),
        migrations.AddField(
            model_name='rating',
            name='seat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rating.Seat'),
        ),
    ]
