# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-09 18:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0002_auto_20160809_1829'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='beverage',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='legspace',
        ),
    ]
