# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-12 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0003_auto_20160809_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='comment',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
