# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-13 14:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0007_location_parent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cinema',
            old_name='location',
            new_name='parent',
        ),
    ]
