# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-13 14:15
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0010_auto_20161013_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinema',
            name='parent',
            field=mptt.fields.TreeForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='rating.Location', verbose_name='Location'),
        ),
    ]
