# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-13 14:17
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0011_auto_20161013_1415'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hall',
            name='cinema',
        ),
        migrations.RemoveField(
            model_name='row',
            name='hall',
        ),
        migrations.RemoveField(
            model_name='seat',
            name='row',
        ),
        migrations.AddField(
            model_name='hall',
            name='parent',
            field=mptt.fields.TreeForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cinema', to='rating.Cinema', verbose_name='Cinema'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='row',
            name='parent',
            field=mptt.fields.TreeForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='hall', to='rating.Hall', verbose_name='Hall'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seat',
            name='parent',
            field=mptt.fields.TreeForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='row', to='rating.Row', verbose_name='Row'),
            preserve_default=False,
        ),
    ]
