# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-13 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0012_auto_20161013_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='row',
            name='seat_count',
            field=models.IntegerField(default=0),
        ),
    ]
