# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-26 12:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0014_auto_20161013_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='view_2d',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='view_3d',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
