# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-26 12:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0015_auto_20161026_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='comment',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='view_2d',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='view_3d',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
