# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-28 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0016_auto_20161026_1239'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('mail', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(max_length=200, verbose_name='Stadt')),
                ('cinema', models.CharField(max_length=200, verbose_name='Kino')),
                ('comment', models.TextField(blank=True, max_length=500, null=True, verbose_name='Nachricht')),
            ],
        ),
    ]
